apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.persistence.data.accessModes | join ", " }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-config
spec:
  accessModes:
    - {{ .Values.persistence.config.accessModes | join ", " }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
