apiVersion: v1
kind: Service
metadata:
  name: {{ include "threadfin.fullname" . }}
  labels:
    {{- include "threadfin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 34400
      protocol: TCP
      name: http
  selector:
    {{- include "threadfin.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}