apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard-home.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "adguard-home.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "adguard-home.name" . }}
    spec:
      containers:
        - name: adguardhome
          image: "{{ .Values.adguardhome.image.repository }}:{{ .Values.adguardhome.image.tag }}"
          imagePullPolicy: {{ .Values.adguardhome.image.pullPolicy }}
          ports:
            - name: dns
              containerPort: {{ .Values.adguardhome.ports.dns.target }}
              protocol: UDP
            - name: http
              containerPort: {{ .Values.adguardhome.ports.http.target }}
              protocol: TCP
            - name: setup
              containerPort: {{ .Values.adguardhome.ports.setup.target }}
              protocol: TCP
            - name: dhcp
              containerPort: {{ .Values.adguardhome.ports.dhcp.target }}
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/work
            - name: config
              mountPath: /opt/adguardhome/conf
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.fullname" . }}-data
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.fullname" . }}-config
