apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard-home.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "adguard-home.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "adguard-home.name" . }}
    spec:
      initContainers:
        - name: configure-dhcp
          image: mikefarah/yq
          command: ['sh', '/config/adjust-dhcp-option.sh']
          securityContext:
            runAsUser: 0  # Ensure the init container runs as root            
          env:
            - name: LOADBALANCER_IP
              value: "{{ .Values.adguardhome.service.loadBalancerIP }}"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: script-volume
              mountPath: /config/adjust-dhcp-option.sh
              subPath: adjust-dhcp-option.sh
      containers:
        - name: adguardhome
          image: "{{ .Values.adguardhome.image.repository }}:{{ .Values.adguardhome.image.tag }}"
          imagePullPolicy: {{ .Values.adguardhome.image.pullPolicy }}
          ports:
            - name: dns
              containerPort: {{ .Values.adguardhome.ports.dns.target }}
              protocol: UDP
            - name: http
              containerPort: {{ .Values.adguardhome.ports.http.target }}
              protocol: TCP
            - name: setup
              containerPort: {{ .Values.adguardhome.ports.setup.target }}
              protocol: TCP
            - name: dhcp
              containerPort: {{ .Values.adguardhome.ports.dhcp.target }}
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /opt/adguardhome/conf
            - name: data
              mountPath: /opt/adguardhome/work
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.fullname" . }}-data
        - name: script-volume
          configMap:
            name: dhcp-config-script
