apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}
  annotations:
    # Utilisation de l'annotation pour une seule IP IPv4 avec MetalLB
    metallb.universe.tf/loadBalancerIPs: {{ .Values.adguardhome.service.loadBalancerIP }}
spec:
  type: {{ .Values.adguardhome.service.type }}
  externalTrafficPolicy: Local
  ports:
    - name: dns
      port: 53
      targetPort: {{ .Values.adguardhome.ports.dns.target }}
      protocol: UDP
    - name: http
      port: 80
      targetPort: {{ .Values.adguardhome.ports.http.target }}
      protocol: TCP
    - name: setup
      port: 3000
      targetPort: {{ .Values.adguardhome.ports.setup.target }}
      protocol: TCP
    - name: dhcp
      port: 67
      targetPort: {{ .Values.adguardhome.ports.dhcp.target }}
      protocol: UDP
  selector:
    app: {{ include "adguard-home.name" . }}
